-- MySQL Script generated by MySQL Workbench
-- 09/06/21 18:44:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_Control_Escolar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DB_Control_Escolar` ;

-- -----------------------------------------------------
-- Schema DB_Control_Escolar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Control_Escolar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DB_Control_Escolar` ;

-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Direccion` (
  `Id_Direccion` INT NOT NULL AUTO_INCREMENT,
  `Estado` VARCHAR(60) NOT NULL,
  `Municipio` VARCHAR(60) NOT NULL,
  `Calle` VARCHAR(100) NOT NULL,
  `Numero` VARCHAR(10) NULL,
  `CP` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_Direccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Rol` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Rol` (
  `Id_Rol` INT NOT NULL AUTO_INCREMENT,
  `Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Genero` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Genero` (
  `Id_Genero` INT NOT NULL AUTO_INCREMENT,
  `Genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Estatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Estatus` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Estatus` (
  `Id_Estatus` INT NOT NULL AUTO_INCREMENT,
  `Estatus` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Id_Estatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Usuario` (
  `Id_Usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(60) NOT NULL,
  `Apellido_Paterno` VARCHAR(60) NOT NULL,
  `Apellido_Materno` VARCHAR(60) NOT NULL,
  `Correo` VARCHAR(100) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  `Foto` BLOB NULL,
  `Contrasena` VARCHAR(65) NOT NULL,
  `Id_Direccion` INT NOT NULL,
  `Id_Rol` INT NOT NULL,
  `Id_Genero` INT NOT NULL,
  `Id_Estatus` INT NOT NULL,
  PRIMARY KEY (`Id_Usuario`, `Id_Direccion`, `Id_Rol`, `Id_Genero`, `Id_Estatus`),
  CONSTRAINT `fk_Usuario_Direccion`
    FOREIGN KEY (`Id_Direccion`)
    REFERENCES `DB_Control_Escolar`.`Direccion` (`Id_Direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Rol1`
    FOREIGN KEY (`Id_Rol`)
    REFERENCES `DB_Control_Escolar`.`Rol` (`Id_Rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Genero1`
    FOREIGN KEY (`Id_Genero`)
    REFERENCES `DB_Control_Escolar`.`Genero` (`Id_Genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Estatus1`
    FOREIGN KEY (`Id_Estatus`)
    REFERENCES `DB_Control_Escolar`.`Estatus` (`Id_Estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Usuario_Direccion_idx` ON `DB_Control_Escolar`.`Usuario` (`Id_Direccion` ASC);

CREATE INDEX `fk_Usuario_Rol1_idx` ON `DB_Control_Escolar`.`Usuario` (`Id_Rol` ASC);

CREATE INDEX `fk_Usuario_Genero1_idx` ON `DB_Control_Escolar`.`Usuario` (`Id_Genero` ASC);

CREATE INDEX `fk_Usuario_Estatus1_idx` ON `DB_Control_Escolar`.`Usuario` (`Id_Estatus` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Personal_Escolar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Personal_Escolar` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Personal_Escolar` (
  `Id_Personal_Escolar` INT NOT NULL AUTO_INCREMENT,
  `RFC` VARCHAR(10) NOT NULL,
  `Puesto` VARCHAR(60) NULL,
  `Id_Usuario` INT NOT NULL,
  PRIMARY KEY (`Id_Personal_Escolar`, `Id_Usuario`),
  CONSTRAINT `fk_Docente_Usuario1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `DB_Control_Escolar`.`Usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Docente_Usuario1_idx` ON `DB_Control_Escolar`.`Personal_Escolar` (`Id_Usuario` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Nivel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Nivel` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Nivel` (
  `Id_Nivel` INT NOT NULL AUTO_INCREMENT,
  `Nivel` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Id_Nivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Grado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Grado` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Grado` (
  `Id_Grado` INT NOT NULL AUTO_INCREMENT,
  `Grado` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_Grado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Alumno` (
  `Id_Alumno` INT NOT NULL AUTO_INCREMENT,
  `RFC` VARCHAR(10) NOT NULL,
  `Id_Usuario` INT NOT NULL,
  `Id_Nivel` INT NOT NULL,
  `Id_Grado` INT NOT NULL,
  PRIMARY KEY (`Id_Alumno`, `Id_Usuario`, `Id_Nivel`, `Id_Grado`),
  CONSTRAINT `fk_Alumno_Usuario1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `DB_Control_Escolar`.`Usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Nivel1`
    FOREIGN KEY (`Id_Nivel`)
    REFERENCES `DB_Control_Escolar`.`Nivel` (`Id_Nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Grado1`
    FOREIGN KEY (`Id_Grado`)
    REFERENCES `DB_Control_Escolar`.`Grado` (`Id_Grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Alumno_Usuario1_idx` ON `DB_Control_Escolar`.`Alumno` (`Id_Usuario` ASC);

CREATE INDEX `fk_Alumno_Nivel1_idx` ON `DB_Control_Escolar`.`Alumno` (`Id_Nivel` ASC);

CREATE INDEX `fk_Alumno_Grado1_idx` ON `DB_Control_Escolar`.`Alumno` (`Id_Grado` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Periodo` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Periodo` (
  `Id_Periodo` INT NOT NULL AUTO_INCREMENT,
  `Fecha_Inicio` DATE NOT NULL,
  `Fecha_Termino` DATE NOT NULL,
  PRIMARY KEY (`Id_Periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Horario_Clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Horario_Clase` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Horario_Clase` (
  `Id_Horario_Clase` INT NOT NULL AUTO_INCREMENT,
  `Dias` VARCHAR(100) NOT NULL,
  `Horas` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id_Horario_Clase`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Clase` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Clase` (
  `Id_Clase` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Clase` VARCHAR(100) NOT NULL,
  `Descripción` LONGTEXT NULL,
  `Codigo_Clase` VARCHAR(7) NOT NULL,
  `Id_Nivel` INT NOT NULL,
  `Id_Grado` INT NOT NULL,
  `Id_Personal_Escolar` INT NOT NULL,
  `Id_Estatus` INT NOT NULL,
  `Id_Periodo` INT NOT NULL,
  `Id_Horario_Clase` INT NOT NULL,
  PRIMARY KEY (`Id_Clase`, `Id_Nivel`, `Id_Grado`, `Id_Personal_Escolar`, `Id_Estatus`, `Id_Periodo`, `Id_Horario_Clase`),
  CONSTRAINT `fk_Clase_Nivel1`
    FOREIGN KEY (`Id_Nivel`)
    REFERENCES `DB_Control_Escolar`.`Nivel` (`Id_Nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clase_Grado1`
    FOREIGN KEY (`Id_Grado`)
    REFERENCES `DB_Control_Escolar`.`Grado` (`Id_Grado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clase_Personal_Escolar1`
    FOREIGN KEY (`Id_Personal_Escolar`)
    REFERENCES `DB_Control_Escolar`.`Personal_Escolar` (`Id_Personal_Escolar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clase_Estatus1`
    FOREIGN KEY (`Id_Estatus`)
    REFERENCES `DB_Control_Escolar`.`Estatus` (`Id_Estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clase_Periodo1`
    FOREIGN KEY (`Id_Periodo`)
    REFERENCES `DB_Control_Escolar`.`Periodo` (`Id_Periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clase_Horario_Clase1`
    FOREIGN KEY (`Id_Horario_Clase`)
    REFERENCES `DB_Control_Escolar`.`Horario_Clase` (`Id_Horario_Clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Clase_Nivel1_idx` ON `DB_Control_Escolar`.`Clase` (`Id_Nivel` ASC);

CREATE INDEX `fk_Clase_Grado1_idx` ON `DB_Control_Escolar`.`Clase` (`Id_Grado` ASC);

CREATE INDEX `fk_Clase_Personal_Escolar1_idx` ON `DB_Control_Escolar`.`Clase` (`Id_Personal_Escolar` ASC);

CREATE INDEX `fk_Clase_Estatus1_idx` ON `DB_Control_Escolar`.`Clase` (`Id_Estatus` ASC);

CREATE INDEX `fk_Clase_Periodo1_idx` ON `DB_Control_Escolar`.`Clase` (`Id_Periodo` ASC);

CREATE INDEX `fk_Clase_Horario_Clase1_idx` ON `DB_Control_Escolar`.`Clase` (`Id_Horario_Clase` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Alumno_Clase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Alumno_Clase` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Alumno_Clase` (
  `Id_Alumno_Clase` INT NOT NULL AUTO_INCREMENT,
  `Id_Alumno` INT NOT NULL,
  `Id_Clase` INT NOT NULL,
  PRIMARY KEY (`Id_Alumno_Clase`, `Id_Alumno`, `Id_Clase`),
  CONSTRAINT `fk_Alumno_Clase_Alumno1`
    FOREIGN KEY (`Id_Alumno`)
    REFERENCES `DB_Control_Escolar`.`Alumno` (`Id_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_Clase_Clase1`
    FOREIGN KEY (`Id_Clase`)
    REFERENCES `DB_Control_Escolar`.`Clase` (`Id_Clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Alumno_Clase_Alumno1_idx` ON `DB_Control_Escolar`.`Alumno_Clase` (`Id_Alumno` ASC);

CREATE INDEX `fk_Alumno_Clase_Clase1_idx` ON `DB_Control_Escolar`.`Alumno_Clase` (`Id_Clase` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Recurso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Recurso` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Recurso` (
  `Id_Recurso` INT NOT NULL AUTO_INCREMENT,
  `Link_Recurso` LONGTEXT NOT NULL,
  PRIMARY KEY (`Id_Recurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Actividad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Actividad` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Actividad` (
  `Id_Actividad` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Actividad` VARCHAR(60) NOT NULL,
  `Contenido` LONGTEXT NOT NULL,
  `Fecha_Entrega` DATE NULL,
  `Id_Personal_Escolar` INT NOT NULL,
  `Id_Clase` INT NOT NULL,
  `Id_Recurso` INT NOT NULL,
  PRIMARY KEY (`Id_Actividad`, `Id_Personal_Escolar`, `Id_Clase`, `Id_Recurso`),
  CONSTRAINT `fk_Actividad_Personal_Escolar1`
    FOREIGN KEY (`Id_Personal_Escolar`)
    REFERENCES `DB_Control_Escolar`.`Personal_Escolar` (`Id_Personal_Escolar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Clase1`
    FOREIGN KEY (`Id_Clase`)
    REFERENCES `DB_Control_Escolar`.`Clase` (`Id_Clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Actividad_Recurso1`
    FOREIGN KEY (`Id_Recurso`)
    REFERENCES `DB_Control_Escolar`.`Recurso` (`Id_Recurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Actividad_Personal_Escolar1_idx` ON `DB_Control_Escolar`.`Actividad` (`Id_Personal_Escolar` ASC);

CREATE INDEX `fk_Actividad_Clase1_idx` ON `DB_Control_Escolar`.`Actividad` (`Id_Clase` ASC);

CREATE INDEX `fk_Actividad_Recurso1_idx` ON `DB_Control_Escolar`.`Actividad` (`Id_Recurso` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Biblioteca_Virtual`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Biblioteca_Virtual` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Biblioteca_Virtual` (
  `Id_Biblioteca_Virtual` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Material` VARCHAR(100) NOT NULL,
  `Descripcion_Material` VARCHAR(100) NOT NULL,
  `Id_Estatus` INT NOT NULL,
  `Id_Recurso` INT NOT NULL,
  `Id_Clase` INT NOT NULL,
  PRIMARY KEY (`Id_Biblioteca_Virtual`, `Id_Estatus`, `Id_Recurso`, `Id_Clase`),
  CONSTRAINT `fk_Biblioteca_Virtual_Estatus1`
    FOREIGN KEY (`Id_Estatus`)
    REFERENCES `DB_Control_Escolar`.`Estatus` (`Id_Estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Biblioteca_Virtual_Recurso1`
    FOREIGN KEY (`Id_Recurso`)
    REFERENCES `DB_Control_Escolar`.`Recurso` (`Id_Recurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Biblioteca_Virtual_Clase1`
    FOREIGN KEY (`Id_Clase`)
    REFERENCES `DB_Control_Escolar`.`Clase` (`Id_Clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Biblioteca_Virtual_Estatus1_idx` ON `DB_Control_Escolar`.`Biblioteca_Virtual` (`Id_Estatus` ASC);

CREATE INDEX `fk_Biblioteca_Virtual_Recurso1_idx` ON `DB_Control_Escolar`.`Biblioteca_Virtual` (`Id_Recurso` ASC);

CREATE INDEX `fk_Biblioteca_Virtual_Clase1_idx` ON `DB_Control_Escolar`.`Biblioteca_Virtual` (`Id_Clase` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Tipo_Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Tipo_Pago` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Tipo_Pago` (
  `Id_Tipo_Pago` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Pago` VARCHAR(45) NULL,
  PRIMARY KEY (`Id_Tipo_Pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Pago` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Pago` (
  `Id_Pago` INT NOT NULL AUTO_INCREMENT,
  `Descripcion_Pago` LONGTEXT NOT NULL,
  `Total_Pago` DECIMAL(11) NOT NULL,
  `Fecha_Pago` DATE NOT NULL,
  `Id_Tipo_Pago` INT NOT NULL,
  PRIMARY KEY (`Id_Pago`, `Id_Tipo_Pago`),
  CONSTRAINT `fk_Pago_Tipo_Pago1`
    FOREIGN KEY (`Id_Tipo_Pago`)
    REFERENCES `DB_Control_Escolar`.`Tipo_Pago` (`Id_Tipo_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pago_Tipo_Pago1_idx` ON `DB_Control_Escolar`.`Pago` (`Id_Tipo_Pago` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Padre_Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Padre_Alumno` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Padre_Alumno` (
  `Id_Padre_Alumno` INT NOT NULL AUTO_INCREMENT,
  `Id_Alumno` INT NOT NULL,
  `Id_Padre` INT NOT NULL,
  `Id_Pago` INT NOT NULL,
  PRIMARY KEY (`Id_Padre_Alumno`, `Id_Alumno`, `Id_Padre`, `Id_Pago`),
  CONSTRAINT `fk_Padre_Alumno_Alumno1`
    FOREIGN KEY (`Id_Alumno`)
    REFERENCES `DB_Control_Escolar`.`Alumno` (`Id_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Padre_Alumno_Usuario1`
    FOREIGN KEY (`Id_Padre`)
    REFERENCES `DB_Control_Escolar`.`Usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Padre_Alumno_Pago1`
    FOREIGN KEY (`Id_Pago`)
    REFERENCES `DB_Control_Escolar`.`Pago` (`Id_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Padre_Alumno_Alumno1_idx` ON `DB_Control_Escolar`.`Padre_Alumno` (`Id_Alumno` ASC);

CREATE INDEX `fk_Padre_Alumno_Usuario1_idx` ON `DB_Control_Escolar`.`Padre_Alumno` (`Id_Padre` ASC);

CREATE INDEX `fk_Padre_Alumno_Pago1_idx` ON `DB_Control_Escolar`.`Padre_Alumno` (`Id_Pago` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Parcial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Parcial` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Parcial` (
  `Id_Parcial` INT NOT NULL AUTO_INCREMENT,
  `Parcial` VARCHAR(5) NULL,
  PRIMARY KEY (`Id_Parcial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Calificacion_Parcial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Calificacion_Parcial` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Calificacion_Parcial` (
  `Id_Calificacion_Parcial` INT NOT NULL AUTO_INCREMENT,
  `Calificacion` DECIMAL(11) NOT NULL,
  `Id_Alumno` INT NOT NULL,
  `Id_Alumno_Clase` INT NOT NULL,
  `Id_Parcial` INT NOT NULL,
  PRIMARY KEY (`Id_Calificacion_Parcial`, `Id_Alumno`, `Id_Alumno_Clase`, `Id_Parcial`),
  CONSTRAINT `fk_Calificacion_Parcial_Alumno1`
    FOREIGN KEY (`Id_Alumno`)
    REFERENCES `DB_Control_Escolar`.`Alumno` (`Id_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificacion_Parcial_Alumno_Clase1`
    FOREIGN KEY (`Id_Alumno_Clase`)
    REFERENCES `DB_Control_Escolar`.`Alumno_Clase` (`Id_Alumno_Clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificacion_Parcial_Parcial1`
    FOREIGN KEY (`Id_Parcial`)
    REFERENCES `DB_Control_Escolar`.`Parcial` (`Id_Parcial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Calificacion_Parcial_Alumno1_idx` ON `DB_Control_Escolar`.`Calificacion_Parcial` (`Id_Alumno` ASC);

CREATE INDEX `fk_Calificacion_Parcial_Alumno_Clase1_idx` ON `DB_Control_Escolar`.`Calificacion_Parcial` (`Id_Alumno_Clase` ASC);

CREATE INDEX `fk_Calificacion_Parcial_Parcial1_idx` ON `DB_Control_Escolar`.`Calificacion_Parcial` (`Id_Parcial` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Calificacion_Final`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Calificacion_Final` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Calificacion_Final` (
  `Id_Calificacion_Final` INT NOT NULL AUTO_INCREMENT,
  `Calificacion` DECIMAL(11) NOT NULL,
  `Id_Alumno` INT NOT NULL,
  `Id_Alumno_Clase` INT NOT NULL,
  PRIMARY KEY (`Id_Calificacion_Final`, `Id_Alumno`, `Id_Alumno_Clase`),
  CONSTRAINT `fk_Calificacion_Final_Alumno1`
    FOREIGN KEY (`Id_Alumno`)
    REFERENCES `DB_Control_Escolar`.`Alumno` (`Id_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calificacion_Final_Alumno_Clase1`
    FOREIGN KEY (`Id_Alumno_Clase`)
    REFERENCES `DB_Control_Escolar`.`Alumno_Clase` (`Id_Alumno_Clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Calificacion_Final_Alumno1_idx` ON `DB_Control_Escolar`.`Calificacion_Final` (`Id_Alumno` ASC);

CREATE INDEX `fk_Calificacion_Final_Alumno_Clase1_idx` ON `DB_Control_Escolar`.`Calificacion_Final` (`Id_Alumno_Clase` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Tipo_Asistenciaa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Tipo_Asistenciaa` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Tipo_Asistenciaa` (
  `Id_Tipo_Asistencia` INT NOT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_Tipo_Asistencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Asistencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Asistencia` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Asistencia` (
  `Id_Asistencia` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Id_Alumno` INT NOT NULL,
  `Id_Personal_Escolar` INT NOT NULL,
  `Id_Alumno_Clase` INT NOT NULL,
  `Id_Tipo_Asistencia` INT NOT NULL,
  PRIMARY KEY (`Id_Asistencia`, `Id_Alumno`, `Id_Personal_Escolar`, `Id_Alumno_Clase`, `Id_Tipo_Asistencia`),
  CONSTRAINT `fk_Asistencia_Alumno1`
    FOREIGN KEY (`Id_Alumno`)
    REFERENCES `DB_Control_Escolar`.`Alumno` (`Id_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistencia_Personal_Escolar1`
    FOREIGN KEY (`Id_Personal_Escolar`)
    REFERENCES `DB_Control_Escolar`.`Personal_Escolar` (`Id_Personal_Escolar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistencia_Alumno_Clase1`
    FOREIGN KEY (`Id_Alumno_Clase`)
    REFERENCES `DB_Control_Escolar`.`Alumno_Clase` (`Id_Alumno_Clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asistencia_Tipo_Asistenciaa1`
    FOREIGN KEY (`Id_Tipo_Asistencia`)
    REFERENCES `DB_Control_Escolar`.`Tipo_Asistenciaa` (`Id_Tipo_Asistencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Asistencia_Alumno1_idx` ON `DB_Control_Escolar`.`Asistencia` (`Id_Alumno` ASC);

CREATE INDEX `fk_Asistencia_Personal_Escolar1_idx` ON `DB_Control_Escolar`.`Asistencia` (`Id_Personal_Escolar` ASC);

CREATE INDEX `fk_Asistencia_Alumno_Clase1_idx` ON `DB_Control_Escolar`.`Asistencia` (`Id_Alumno_Clase` ASC);

CREATE INDEX `fk_Asistencia_Tipo_Asistenciaa1_idx` ON `DB_Control_Escolar`.`Asistencia` (`Id_Tipo_Asistencia` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Evaluacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Evaluacion` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Evaluacion` (
  `Id_Evaluación` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Evaluacion` VARCHAR(60) NOT NULL,
  `Descripcion` LONGTEXT NOT NULL,
  `Link_Evaluacion` VARCHAR(100) NOT NULL,
  `Id_Recurso` INT NULL,
  `Id_Clase` INT NOT NULL,
  PRIMARY KEY (`Id_Evaluación`, `Id_Recurso`, `Id_Clase`),
  CONSTRAINT `fk_Evaluacion_Recurso1`
    FOREIGN KEY (`Id_Recurso`)
    REFERENCES `DB_Control_Escolar`.`Recurso` (`Id_Recurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluacion_Clase1`
    FOREIGN KEY (`Id_Clase`)
    REFERENCES `DB_Control_Escolar`.`Clase` (`Id_Clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Evaluacion_Recurso1_idx` ON `DB_Control_Escolar`.`Evaluacion` (`Id_Recurso` ASC);

CREATE INDEX `fk_Evaluacion_Clase1_idx` ON `DB_Control_Escolar`.`Evaluacion` (`Id_Clase` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Revision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Revision` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Revision` (
  `Id_Revision` INT NOT NULL AUTO_INCREMENT,
  `Retroalimentación` LONGTEXT NULL,
  `Link_Revision` VARCHAR(100) NULL,
  `Calificacion` DECIMAL NOT NULL,
  `Id_Evaluación` INT NOT NULL,
  `Id_Alumno_Clase` INT NOT NULL,
  PRIMARY KEY (`Id_Revision`, `Id_Evaluación`, `Id_Alumno_Clase`),
  CONSTRAINT `fk_Revision_Evaluacion1`
    FOREIGN KEY (`Id_Evaluación`)
    REFERENCES `DB_Control_Escolar`.`Evaluacion` (`Id_Evaluación`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Revision_Alumno_Clase1`
    FOREIGN KEY (`Id_Alumno_Clase`)
    REFERENCES `DB_Control_Escolar`.`Alumno_Clase` (`Id_Alumno_Clase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Revision_Evaluacion1_idx` ON `DB_Control_Escolar`.`Revision` (`Id_Evaluación` ASC);

CREATE INDEX `fk_Revision_Alumno_Clase1_idx` ON `DB_Control_Escolar`.`Revision` (`Id_Alumno_Clase` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Mensaje` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Mensaje` (
  `Id_Mensaje` INT NOT NULL AUTO_INCREMENT,
  `Contenido` LONGTEXT NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Id_Usuario_remitente` INT NOT NULL,
  `Id_Usuario_destinatario` INT NOT NULL,
  `Id_Estatus` INT NOT NULL,
  PRIMARY KEY (`Id_Mensaje`, `Id_Usuario_remitente`, `Id_Usuario_destinatario`, `Id_Estatus`),
  CONSTRAINT `fk_Mensaje_Usuario1`
    FOREIGN KEY (`Id_Usuario_remitente`)
    REFERENCES `DB_Control_Escolar`.`Usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_Usuario2`
    FOREIGN KEY (`Id_Usuario_destinatario`)
    REFERENCES `DB_Control_Escolar`.`Usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mensaje_Estatus1`
    FOREIGN KEY (`Id_Estatus`)
    REFERENCES `DB_Control_Escolar`.`Estatus` (`Id_Estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Mensaje_Usuario1_idx` ON `DB_Control_Escolar`.`Mensaje` (`Id_Usuario_remitente` ASC);

CREATE INDEX `fk_Mensaje_Usuario2_idx` ON `DB_Control_Escolar`.`Mensaje` (`Id_Usuario_destinatario` ASC);

CREATE INDEX `fk_Mensaje_Estatus1_idx` ON `DB_Control_Escolar`.`Mensaje` (`Id_Estatus` ASC);


-- -----------------------------------------------------
-- Table `DB_Control_Escolar`.`Notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DB_Control_Escolar`.`Notificacion` ;

CREATE TABLE IF NOT EXISTS `DB_Control_Escolar`.`Notificacion` (
  `Id_Notificacion` INT NOT NULL AUTO_INCREMENT,
  `Contenido` LONGTEXT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Id_Estatus` INT NOT NULL,
  `Id_Usuario` INT NOT NULL,
  PRIMARY KEY (`Id_Notificacion`, `Id_Estatus`, `Id_Usuario`),
  CONSTRAINT `fk_Notificacion_Estatus1`
    FOREIGN KEY (`Id_Estatus`)
    REFERENCES `DB_Control_Escolar`.`Estatus` (`Id_Estatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notificacion_Usuario1`
    FOREIGN KEY (`Id_Usuario`)
    REFERENCES `DB_Control_Escolar`.`Usuario` (`Id_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Notificacion_Estatus1_idx` ON `DB_Control_Escolar`.`Notificacion` (`Id_Estatus` ASC);

CREATE INDEX `fk_Notificacion_Usuario1_idx` ON `DB_Control_Escolar`.`Notificacion` (`Id_Usuario` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
